export const productData = [
  {
    "id": 1,
    "brand": "colourpop",
    "name": "Lippie Pencil",
    "price": "5.0",
    "price_sign": "$",
    "currency": "CAD",
    "image_link": "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
    "description": "Lippie Pencil A long-wearing and high-intensity lip pencil that glides on easily and prevents feathering. Many of our Lippie Stix have a coordinating Lippie Pencil designed to compliment it perfectly, but feel free to mix and match!",
    "rating": null,
    "category": "pencil",
    "product_type": "lip_liner",
    'inCart': false,
    'total': 0,
    'count': 0
  },
  {
    "id": 2,
    "brand": "colourpop",
    "name": "Blotted Lip",
    "price": "5.5",
    "price_sign": "$",
    "currency": "CAD",
    "image_link": "https://cdn.shopify.com/s/files/1/1338/0845/products/brain-freeze_a_800x1200.jpg?v=1502255076",
    "description": "Blotted Lip Sheer matte lipstick that creates the perfect popsicle pout! Formula is lightweight, matte and buildable for light to medium coverage.",
    "rating": null,
    "category": "lipstick",
    "product_type": "lipstick",
    'inCart': false,
    'total': 0,
    'count': 0
  },
  {
    "id": 3,
    "brand": "colourpop",
    "name": "Lippie Stix",
    "price": "5.5",
    "price_sign": "$",
    "currency": "CAD",
    "image_link": "https://cdn.shopify.com/s/files/1/1338/0845/collections/blottedlip-lippie-stix_grande.jpg?v=1512588803",
    "description": "Lippie Stix Formula contains Vitamin E, Mango, Avocado, and Shea butter for added comfort and moisture. None of our Lippie formulas contain any nasty ingredients like Parabens or Sulfates.",
    "rating": null,
    "category": "lipstick",
    "product_type": "lipstick",
    'inCart': false,
    'total': 0,
    'count': 0
  },
  {
    "id": 4,
    "brand": "clinique",
    "name": "High Impact™ Custom Black Kajal",
    "price": "17.5",
    "price_sign": "$",
    "currency": "USD",
    "image_link": "https://www.clinique.com/media/export/cms/products/181x209/clq_ZP4R01_181x209.png",
    "description": "For kicked-up eye drama, go bold and black. Pigment-packed kajal pencil delivers rich, dark colour with 12 hours of staying power. Skip-proof formula resists smudging, sweat and humidity—even water. Ophthalmologist Tested. Appropriate for sensitive eyes and contact lens wearers, too.",
    "rating": null,
    "category": null,
    "product_type": "eyeliner",
    'inCart': false,
    'total': 0,
    'count': 0
  },
  {
    "id": 5,
    "brand": "physicians formula",
    "name": "Physicians Formula Nude Wear Touch of Glow Palette in Light",
    "price": "19.99",
    "price_sign": null,
    "currency": null,
    "image_link": "https://d3t32hsnjxo7q6.cloudfront.net/i/490e2f5a880ab9d39c44876a0ea89f44_ra,w158,h184_pa,w158,h184.jpg",
    "rating": 3.8,
    "category": null,
    "product_type": "bronzer",
    'inCart': false,
    'total': 0,
    'count': 0
  },
  {
    "id": 6,
    "brand": "clinique",
    "name": "High Impact™ Custom Black Kajal",
    "price": "17.5",
    "price_sign": "$",
    "currency": "USD",
    "image_link": "https://www.clinique.com/media/export/cms/products/181x209/clq_ZP4R01_181x209.png",
    "description": "For kicked-up eye drama, go bold and black. Pigment-packed kajal pencil delivers rich, dark colour with 12 hours of staying power. Skip-proof formula resists smudging, sweat and humidity—even water. Ophthalmologist Tested. Appropriate for sensitive eyes and contact lens wearers, too.",
    "rating": null,
    "category": null,
    "product_type": "eyeshadow",
    'inCart': false,
    'total': 0,
    'count': 0
  },
  {
    "id": 7,
    "brand": "physicians formula",
    "name": "Physicians Formula Mineral Wear Airbrushing Blush",
    "price": "15.49",
    "price_sign": null,
    "currency": null,
    "image_link": "https://d3t32hsnjxo7q6.cloudfront.net/i/e096eb4264561b76a90a9a2bfb6cfca2_ra,w158,h184_pa,w158,h184.jpeg", "product_link": "https://well.ca/products/physicians-formula-mineral-wear_70987.html",
    "rating": 4.8,
    "category": "powder",
    "product_type": "blush",
    'inCart': false,
    'total': 0,
    'count': 0
  },
  {
    "id": 8,
    "brand": "clinique",
    "name": "Chubby Stick\u0026trade; Moisturizing Lip Colour Balm",
    "price": "17.5",
    "price_sign": "$",
    "currency": "USD",
    "image_link": "https://www.clinique.com/media/export/cms/products/181x209/clq_749K01_181x209.png",
    "description": "Super-nourishing balm is loaded with mango and shea butters. Just what dry, delicate lips need to feel comfortably soft and smooth. Natural-looking lip tints have a subtle sheen.",
    "rating": null,
    "category": "lipstick",
    "product_type": "lipstick",
    'inCart': false,
    'total': 0,
    'count': 0
  },
  {
    "id": 9,
    "brand": "clinique",
    "name": "Clinique Pop™ Matte Lip Colour + Primer",
    "price": "18.5",
    "price_sign": "$",
    "currency": "USD",
    "image_link": "https://www.clinique.com/media/export/cms/products/181x209/clq_ZTPH01_181x209.png",
    "description": "Weightless yet pigment-saturated formula hugs lips with 8 hours of creamy matte comfort. Built-in primer helps smooth lips for an easy, even glide every time.",
    "rating": null,
    "category": "lipstick",
    "product_type": "lipstick",
    'inCart': false,
    'total': 0,
    'count': 0
  },
  {
    "id": 10,
    "brand": "clinique",
    "name": "Clinique Pop\u0026trade; Lip Colour + Primer",
    "price": "18.5",
    "price_sign": "$",
    "currency": "USD",
    "image_link": "https://www.clinique.com/media/export/cms/products/181x209/clq_ZEK2_181x209.png",
    "description": "Luxurious yet weightless formula merges bold, saturated colour with a smoothing primer. Glides on effortlessly to a modern-velvet finish. Colour stays true, keeps lips comfortably moisturized for 8 hours. Allergy Tested. 100% Fragrance Free.",
    "rating": null,
    "category": "lipstick",
    "product_type": "lipstick",
    'inCart': false,
    'total': 0,
    'count': 0
  },
  {
    "id": 11,
    "brand": "clinique",
    "name": "High Impact™ Custom Black Kajal",
    "price": "17.5",
    "price_sign": "$",
    "currency": "USD",
    "image_link": "https://www.clinique.com/media/export/cms/products/181x209/clq_ZP4R01_181x209.png",
    "description": "For kicked-up eye drama, go bold and black. Pigment-packed kajal pencil delivers rich, dark colour with 12 hours of staying power. Skip-proof formula resists smudging, sweat and humidity—even water. Ophthalmologist Tested. Appropriate for sensitive eyes and contact lens wearers, too.",
    "rating": null,
    "category": null,
    "product_type": "mascara",
    'inCart': false,
    'total': 0,
    'count': 0
  },
  {
    "id": 12,
    "brand": "clinique",
    "name": "Clinique Pop\u0026trade; Lip Shadow Cushion Matte Lip",
    "price": "19.5",
    "price_sign": "$",
    "currency": "USD",
    "image_link": "https://www.clinique.com/media/export/cms/products/181x209/clq_ZXH101_181x209.png",
    "description": "Clinique Pop™ Lip Shadow is a weightless matte powder that delivers bold, highly pigmented lip color.",
    "rating": null,
    "category": "lipstick",
    "product_type": "lipstick",
    'inCart': false,
    'total': 0,
    'count': 0
  },
  {
    "id": 13,
    "brand": "dior",
    "name": "\n                            Junon\n                            ",
    "price": "20.0",
    "price_sign": "£",
    "currency": "GBP",
    "image_link": "https://www.dior.com/beauty/version-5.1432748111912/resize-image/ep/0/214/90/0/v6_packshots_sku_pdg%252FPDG_Y0002959-F000355494.jpg",
    "description": "Discover the new-generation Dior Vernis and its ingenious formula that plays up the gel effect.",
    "rating": null,
    "category": null,
    "product_type": "nail_polish",
    'inCart': false,
    'total': 0,
    'count': 0
  },
  {
    "id": 14,
    "brand": "dior",
    "name": "\n                            Matte\n                            ",
    "price": "20.0",
    "price_sign": "£",
    "currency": "GBP",
    "image_link": "https://www.dior.com/beauty/version-5.1432748111912/resize-image/ep/0/214/90/0/v6_packshots_sku_pdg%252FPDG_Y0002959-F000355999.jpg",
    "description": "Discover the new-generation Dior Vernis and its ingenious formula that accentuates the gel effect.",
    "rating": null,
    "category": null,
    "product_type": "nail_polish",
    'inCart': false,
    'total': 0,
    'count': 0
  },
  {
    "id": 15,
    "brand": "clinique",
    "name": "High Impact™ Custom Black Kajal",
    "price": "17.5",
    "price_sign": "$",
    "currency": "USD",
    "image_link": "https://www.clinique.com/media/export/cms/products/181x209/clq_ZP4R01_181x209.png",
    "description": "For kicked-up eye drama, go bold and black. Pigment-packed kajal pencil delivers rich, dark colour with 12 hours of staying power. Skip-proof formula resists smudging, sweat and humidity—even water. Ophthalmologist Tested. Appropriate for sensitive eyes and contact lens wearers, too.",
    "rating": null,
    "category": null,
    "product_type": "eyelashes",
    'inCart': false,
    'total': 0,
    'count': 0
  },
  {
    "id": 16,
    "brand": "dior",
    "name": "\n                            Poison Metal\n                            ",
    "price": "20.0",
    "price_sign": "£",
    "currency": "GBP",
    "image_link": "https://www.dior.com/beauty/version-5.1432748111912/resize-image/ep/0/214/90/0/packshots%252FPDG_Y0003559_F000355979.jpg",
    "description": "Discover the new-generation Dior Vernis and its ingenious formula that accentuates the gel effect.",
    "rating": null,
    "category": null,
    "product_type": "nail_polish",
    'inCart': false,
    'total': 0,
    'count': 0
  },
  {
    "id": 17,
    "brand": "dior",
    "name": "\n                            Jungle Matte\n                            ",
    "price": "20.0",
    "price_sign": "£",
    "currency": "GBP",
    "image_link": "https://www.dior.com/beauty/version-5.1432748111912/resize-image/ep/0/214/90/0/packshots%252FPDG_Y0003759_F000355614.jpg",
    "description": "Discover the new-generation Dior Vernis and its ingenious formula that accentuates the gel effect.",
    "rating": null,
    "category": null,
    "product_type": "nail_polish",
    'inCart': false,
    'total': 0,
    'count': 0
  },
  {
    "id": 18,
    "brand": "dior",
    "name": "\n                            Miss Satin\n                            ",
    "price": "20.0",
    "price_sign": "£",
    "currency": "GBP",
    "image_link": "https://www.dior.com/beauty/version-5.1432748111912/resize-image/ep/0/214/90/0/packshots%252FPDG_Y0003759_F000355162.jpg",
    "description": "Discover the new-generation Dior Vernis and its ingenious formula that accentuates the gel effect.",
    "rating": null,
    "category": null,
    "product_type": "nail_polish",
    'inCart': false,
    'total': 0,
    'count': 0
  },
  {
    "id": 19,
    "brand": "dior",
    "name": "\n                            Mineral\n                            ",
    "price": "20.0",
    "price_sign": "£",
    "currency": "GBP",
    "image_link": "https://www.dior.com/beauty/version-5.1432748111912/resize-image/ep/0/214/90/0/packshots%252FPDG_Y0003567_F000355201.jpg",
    "description": "Discover the new-generation Dior Vernis and its ingenious formula that plays up the gel effect.",
    "rating": null,
    "category": null,
    "product_type": "nail_polish",
    'inCart': false,
    'total': 0,
    'count': 0
  },
  {
    "id": 20,
    "brand": "zaron",
    "name": "Retractable Eye Liner",
    "price": "20.0",
    "price_sign": "$",
    "currency": "GBP",
    "image_link": "https://www.nyxcosmetics…jpg?sw=390&sh=390&sm=fit",
    "description": "Twist and shout! Renowne…never needs sharpening.",
    "rating": null,
    "category": 'pencil',
    "product_type": "eyeliner",
    'inCart': false,
    'total': 0,
    'count': 0
  },
  {
    "id": 21,
    "brand": "iman",
    "name": "Eye Shadow",
    "price": "25.0",
    "price_sign": "$",
    "currency": "GBP",
    "image_link": "https://www.purpicks.com…02/Ombre-Amazonie-CC.png",
    "description": "organic",
    "rating": null,
    "category": 'pencil',
    "product_type": "eyeshadow",
    'inCart': false,
    'total': 0,
    'count': 0
  },
  {
    "id": 22,
    "brand": "classic",
    "name": "Perfect Lash Mascara",
    "price": "5.0",
    "price_sign": "$",
    "currency": "GBP",
    "image_link": "https://www.purpicks.com…perfect-lash-mascara.png",
    "description": "organic",
    "rating": null,
    "category": 'pencil',
    "product_type": "mascara",
    'inCart': false,
    'total': 0,
    'count': 0
  },
  {
    "id": 23,
    "brand": "classic",
    "name": "Loose Mineral Eyeshadow",
    "price": "15.0",
    "price_sign": "$",
    "currency": "GBP",
    "image_link": "https://www.purpicks.com…8-a2cd-9c8981f5edee1.jpg",
    "description": "organic",
    "rating": null,
    "category": 'pencil',
    "product_type": "eyeshadow",
    'inCart': false,
    'total': 0,
    'count': 0
  },
  {
    "id": 23,
    "brand": "fenty",
    "name": "Pressed Foundation",
    "price": "15.0",
    "price_sign": "$",
    "currency": "GBP",
    "image_link": "https://www.purpicks.com…9-a5ec-f49d6104bcbc1.jpg",
    "description": "A pressed foundation by …nd moisturize the skin.",
    "rating": null,
    "category": 'pencil',
    "product_type": "foundation",
    'inCart': false,
    'total': 0,
    'count': 0
  },
  {
    "id": 24,
    "brand": "mac",
    "name": "SFX Setting Powder",
    "price": "25.0",
    "price_sign": "$",
    "currency": "GBP",
    "image_link": "https://www.nyxcosmetics…jpg?sw=390&sh=390&sm=fit",
    "description": "A pressed foundation by …nd moisturize the skin.",
    "rating": null,
    "category": 'pencil',
    "product_type": "foundation",
    'inCart': false,
    'total': 0,
    'count': 0
  }

]

